spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/todolist
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  port:
    8082



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

