spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/todolist
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port:
    8082



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG